---
 - hosts: all
   become: yes
   tasks:
   - name: Execute the following shell commands
     shell: | 
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg  
        apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        apt-get update
        apt-get install -y docker-ce=18.06.1~ce~3-0~ubuntu
        apt-mark hold docker-ce


         
